In [2]:
import numpy as np 
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [4]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


In [6]:
# minimum dimensions 
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [8]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [11]:
# A matrix of 3*5
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
a.shape

(3, 5)